export const CardGraphData = {
  cardData: [
    {
      title: "Daily Active Users by Language",
      content: "Tracks daily active users for each language.",
      graphType: "line",
      graphData: [
        {
          date: "2024-07-01",
          Spanish: 300,
          French: 200,
          Portuguese: 180,
          English: 250,
          Kannada: 150,
        },
        {
          date: "2024-07-02",
          Spanish: 310,
          French: 210,
          Portuguese: 190,
          English: 260,
          Kannada: 160,
        },
        {
          date: "2024-07-03",
          Spanish: 320,
          French: 220,
          Portuguese: 200,
          English: 270,
          Kannada: 170,
        },
        // Add more data points as needed
      ],
      libraryName: "Apex React",
    },
    {
      title: "Course Completion Rates",
      content: "Track the completion rates of different courses.",
      graphType: "bar",
      graphData: [
        { course: "Beginner Spanish", completionRate: 78 },
        { course: "Intermediate French", completionRate: 85 },
        { course: "Advanced German", completionRate: 62 },
        { course: "Basic Japanese", completionRate: 74 },
        { course: "Conversational Italian", completionRate: 80 },
      ],
      libraryName: "Apex React",
    },
    {
      title: "Assessment Scores Distribution",
      content: "Shows the distribution of assessment scores across users.",
      graphType: "pie",
      graphData: [
        { name: "Score 0-50", value: 15 },
        { name: "Score 51-100", value: 45 },
        { name: "Score 101-150", value: 30 },
        { name: "Score 151-200", value: 10 },
      ],
      libraryName: "Apex React",
    },
    {
      title: "User Feedback Sentiment",
      content: "Analyzes the sentiment of user feedback.",
      graphType: "bar",
      graphData: [
        { sentiment: "Very Satisfied", count: 150 },
        { sentiment: "Satisfied", count: 120 },
        { sentiment: "Neutral", count: 50 },
        { sentiment: "Dissatisfied", count: 20 },
        { sentiment: "Very Dissatisfied", count: 10 },
      ],
      libraryName: "Apex React",
    },
    {
      title: "Content Popularity",
      content: "Visualizes the popularity of different content types.",
      graphType: "line",
      graphData: [
        { month: "January", views: 800 },
        { month: "February", views: 950 },
        { month: "March", views: 1100 },
        { month: "April", views: 1200 },
        { month: "May", views: 1300 },
        { month: "June", views: 1400 },
      ],
      libraryName: "Apex React",
    },
    {
      title: "Average Time Spent Per Course",
      content: "Shows the average time users spend on each course.",
      graphType: "bar",
      graphData: [
        { course: "Beginner Spanish", averageTime: 45 },
        { course: "Intermediate French", averageTime: 55 },
        { course: "Advanced German", averageTime: 40 },
        { course: "Basic Japanese", averageTime: 50 },
        { course: "Conversational Italian", averageTime: 60 },
      ],
      libraryName: "Apex React",
    },
    {
      title: "Quiz Success Rates by Difficulty Level",
      content:
        "Analyzes quiz success rates across different difficulty levels.",
      graphType: "pie",
      graphData: [
        { name: "Easy", value: 60 },
        { name: "Medium", value: 30 },
        { name: "Hard", value: 10 },
      ],
      libraryName: "Apex React",
    },
    {
      title: "Monthly New Users",
      content: "Tracks the number of new users who signed up each month.",
      graphType: "line",
      graphData: [
        { month: "January", newUsers: 100 },
        { month: "February", newUsers: 120 },
        { month: "March", newUsers: 150 },
        { month: "April", newUsers: 130 },
        { month: "May", newUsers: 170 },
        { month: "June", newUsers: 180 },
      ],
      libraryName: "Apex React",
    },
    {
      title: "Course Rating Distribution",
      content: "Shows the distribution of ratings given to courses.",
      graphType: "bar",
      graphData: [
        { rating: "5 stars", count: 200 },
        { rating: "4 stars", count: 150 },
        { rating: "3 stars", count: 75 },
        { rating: "2 stars", count: 25 },
        { rating: "1 star", count: 10 },
      ],
      libraryName: "Apex React",
    },
  ],
};
